name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run eslint & prettier
        run: npm run lint && npm run format:check

      - name: Install Playwright dependencies
        run: npx playwright install-deps

      - name: Run tests
        run: npm test
